apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ing
  namespace: default
spec:
  rules:
  - host:
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: simple-service
            port:
              number: 80
